---
- name: "create backend directory"
  file:
    path: ~/backend
    state: directory

- name: "unarchive backend"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: "install dep"
  shell: |
    cd ~/backend
    npm install
- name: "execute node app"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "config pm2"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu